from __future__ import annotations

import base64
import hashlib
import ipaddress
import logging
import math
import time
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

LOGGER = logging.getLogger(__name__)


PROTOCOL_IDS = {
    "ARP": 1,
    "ICMP": 2,
    "TCP": 6,
    "UDP": 17,
    "DNS": 53,
    "HTTP": 80,
    "TLS": 443,
}


@dataclass(slots=True)
class PacketRecord:
    """Normalized packet shape used by every subsystem."""

    timestamp: float
    src_ip: str
    dst_ip: str
    protocol: str
    length: int
    src_port: int | None = None
    dst_port: int | None = None
    ttl: int | None = None
    dns_query: str | None = None
    payload: bytes = b""
    summary: str = ""
    interface: str = ""
    flags: str = ""
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def payload_preview(self) -> str:
        if not self.payload:
            return ""
        text = self.payload[:96].decode("utf-8", errors="replace")
        return text.replace("\n", "\\n").replace("\r", "\\r")

    @property
    def short_time(self) -> str:
        return datetime.fromtimestamp(self.timestamp).strftime("%H:%M:%S")

    def as_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "protocol": self.protocol,
            "length": self.length,
            "src_port": self.src_port,
            "dst_port": self.dst_port,
            "ttl": self.ttl,
            "dns_query": self.dns_query,
            "payload_b64": base64.b64encode(self.payload[:4096]).decode("ascii"),
            "summary": self.summary,
            "interface": self.interface,
            "flags": self.flags,
            "extra": self.extra,
        }


@dataclass(slots=True)
class ThreatAlert:
    """Security event generated by the analyzer or protocol detectors."""

    alert_id: str
    timestamp: float
    severity: str
    title: str
    description: str
    src_ip: str
    dst_ip: str
    protocol: str
    score: float
    category: str
    evidence: dict[str, Any] = field(default_factory=dict)
    recommended_action: str = "Investigate the source, preserve packet evidence, and validate host telemetry."

    @classmethod
    def create(
        cls,
        *,
        severity: str,
        title: str,
        description: str,
        packet: PacketRecord,
        score: float,
        category: str,
        evidence: dict[str, Any] | None = None,
        recommended_action: str | None = None,
    ) -> "ThreatAlert":
        material = f"{packet.timestamp:.3f}:{packet.src_ip}:{packet.dst_ip}:{title}:{category}"
        alert_id = hashlib.sha1(material.encode("utf-8")).hexdigest()[:16]
        return cls(
            alert_id=alert_id,
            timestamp=packet.timestamp,
            severity=severity,
            title=title,
            description=description,
            src_ip=packet.src_ip,
            dst_ip=packet.dst_ip,
            protocol=packet.protocol,
            score=max(0.0, min(1.0, score)),
            category=category,
            evidence=evidence or {},
            recommended_action=recommended_action
            or "Quarantine if confirmed, collect endpoint logs, and compare with firewall history.",
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "timestamp": self.timestamp,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "protocol": self.protocol,
            "score": self.score,
            "category": self.category,
            "evidence": self.evidence,
            "recommended_action": self.recommended_action,
        }


def payload_entropy(payload: bytes) -> float:
    if not payload:
        return 0.0
    counts = Counter(payload)
    total = len(payload)
    return -sum((count / total) * math.log2(count / total) for count in counts.values())


def is_private_ip(value: str) -> bool:
    try:
        ip = ipaddress.ip_address(value)
    except ValueError:
        return False
    return ip.is_private or ip.is_loopback or ip.is_link_local


class PacketFeatureExtractor:
    """Converts packet records into a compact numeric model feature vector."""

    @staticmethod
    def protocol_number(protocol: str) -> int:
        return PROTOCOL_IDS.get(protocol.upper(), 0)

    @classmethod
    def extract(cls, packet: PacketRecord) -> list[float]:
        hour = datetime.fromtimestamp(packet.timestamp).hour + datetime.fromtimestamp(packet.timestamp).minute / 60
        cyc = 2 * math.pi * hour / 24
        return [
            float(min(packet.length, 65535)),
            float(packet.src_port or 0),
            float(packet.dst_port or 0),
            float(cls.protocol_number(packet.protocol)),
            1.0 if is_private_ip(packet.src_ip) else 0.0,
            1.0 if is_private_ip(packet.dst_ip) else 0.0,
            float(min(len(packet.payload), 4096)),
            payload_entropy(packet.payload),
            float(packet.ttl or 0),
            math.sin(cyc),
            math.cos(cyc),
        ]


class ThreatAnalyzer:
    """Stateful behavioral rules that complement the ML engine."""

    RISKY_PORTS = {
        21: "FTP",
        22: "SSH",
        23: "Telnet",
        25: "SMTP",
        53: "DNS",
        80: "HTTP",
        135: "MSRPC",
        139: "NetBIOS",
        445: "SMB",
        1433: "MSSQL",
        3306: "MySQL",
        3389: "RDP",
        5900: "VNC",
        6379: "Redis",
        9200: "Elasticsearch",
    }

    def __init__(self, window_seconds: int = 90) -> None:
        self.window_seconds = window_seconds
        self.recent_packets: deque[PacketRecord] = deque(maxlen=8000)
        self.port_tracker: dict[str, deque[tuple[float, int]]] = defaultdict(lambda: deque(maxlen=1200))
        self.byte_tracker: dict[str, deque[tuple[float, int]]] = defaultdict(lambda: deque(maxlen=2400))
        self.protocol_counts: Counter[str] = Counter()
        self.alert_cooldowns: dict[str, float] = {}
        self.total_packets = 0
        self.total_bytes = 0
        self.threat_counter: Counter[str] = Counter()

    def analyze(
        self,
        packet: PacketRecord,
        anomaly_score: float,
        payload_findings: list[dict[str, Any]] | None = None,
        arp_findings: list[dict[str, Any]] | None = None,
        dns_findings: list[dict[str, Any]] | None = None,
    ) -> list[ThreatAlert]:
        now = packet.timestamp
        self.total_packets += 1
        self.total_bytes += packet.length
        self.recent_packets.append(packet)
        self.protocol_counts[packet.protocol] += 1

        if packet.dst_port:
            ports = self.port_tracker[packet.src_ip]
            ports.append((now, packet.dst_port))
            self._trim_time_deque(ports, now)

        byte_window = self.byte_tracker[packet.src_ip]
        byte_window.append((now, packet.length))
        self._trim_time_deque(byte_window, now)

        candidates: list[ThreatAlert] = []
        if anomaly_score >= 0.82:
            candidates.append(
                ThreatAlert.create(
                    severity=self._severity_for_score(anomaly_score),
                    title="ML Traffic Anomaly",
                    description="Isolation Forest scored this packet stream outside the learned baseline.",
                    packet=packet,
                    score=anomaly_score,
                    category="ML Anomaly",
                    evidence={"anomaly_score": round(anomaly_score, 3), "features": PacketFeatureExtractor.extract(packet)},
                    recommended_action="Review the packet payload and compare the source host against recent authentication and DNS logs.",
                )
            )

        ports_seen = {port for ts, port in self.port_tracker[packet.src_ip] if now - ts <= 60}
        if len(ports_seen) >= 18:
            score = min(1.0, 0.55 + len(ports_seen) / 90)
            candidates.append(
                ThreatAlert.create(
                    severity=self._severity_for_score(score),
                    title="Port Scan Detected",
                    description=f"{packet.src_ip} touched {len(ports_seen)} unique destination ports in the last minute.",
                    packet=packet,
                    score=score,
                    category="Reconnaissance",
                    evidence={"unique_ports": sorted(ports_seen)[:80]},
                    recommended_action="Block or rate-limit the source while validating whether this was an approved scanner.",
                )
            )

        bytes_in_window = sum(size for ts, size in byte_window if now - ts <= 30)
        if bytes_in_window >= 3_000_000:
            score = min(1.0, bytes_in_window / 8_000_000)
            candidates.append(
                ThreatAlert.create(
                    severity=self._severity_for_score(score),
                    title="High Volume Traffic",
                    description=f"{packet.src_ip} moved {bytes_in_window / 1_000_000:.1f} MB in the last 30 seconds.",
                    packet=packet,
                    score=score,
                    category="Traffic Behavior",
                    evidence={"bytes_30s": bytes_in_window},
                    recommended_action="Check for data staging, backup jobs, or possible exfiltration from the source host.",
                )
            )

        if packet.dst_port in self.RISKY_PORTS and not is_private_ip(packet.src_ip):
            service = self.RISKY_PORTS[packet.dst_port or 0]
            candidates.append(
                ThreatAlert.create(
                    severity="MEDIUM",
                    title=f"Internet Exposure Probe: {service}",
                    description=f"External source {packet.src_ip} contacted sensitive service port {packet.dst_port}.",
                    packet=packet,
                    score=0.58,
                    category="Exposure",
                    evidence={"service": service, "dst_port": packet.dst_port},
                    recommended_action="Validate whether the destination host should expose this service and inspect firewall policy.",
                )
            )

        for finding in payload_findings or []:
            score = float(finding.get("score", 0.66))
            candidates.append(
                ThreatAlert.create(
                    severity=finding.get("severity", self._severity_for_score(score)),
                    title=finding.get("title", "Suspicious Payload"),
                    description=finding.get("description", "Suspicious content was found in packet payload."),
                    packet=packet,
                    score=score,
                    category="Payload",
                    evidence=finding,
                    recommended_action="Preserve the payload and inspect the destination application logs around this timestamp.",
                )
            )

        for finding in (arp_findings or []) + (dns_findings or []):
            score = float(finding.get("score", 0.75))
            candidates.append(
                ThreatAlert.create(
                    severity=finding.get("severity", self._severity_for_score(score)),
                    title=finding.get("title", "Protocol Integrity Alert"),
                    description=finding.get("description", "Protocol integrity detector raised an alert."),
                    packet=packet,
                    score=score,
                    category=finding.get("category", "Protocol Integrity"),
                    evidence=finding,
                    recommended_action=finding.get(
                        "recommended_action",
                        "Validate gateway/DNS trust and compare against independent network telemetry.",
                    ),
                )
            )

        alerts = [alert for alert in candidates if self._cooldown_allows(alert)]
        for alert in alerts:
            self.threat_counter[alert.severity] += 1
        return alerts

    def metrics(self) -> dict[str, Any]:
        now = time.time()
        recent = [packet for packet in self.recent_packets if now - packet.timestamp <= 60]
        top_talkers = Counter(packet.src_ip for packet in recent).most_common(6)
        pps = len(recent) / 60 if recent else 0.0
        return {
            "total_packets": self.total_packets,
            "total_bytes": self.total_bytes,
            "packets_per_second": pps,
            "recent_packets": len(recent),
            "protocol_counts": dict(self.protocol_counts),
            "top_talkers": top_talkers,
            "threats": dict(self.threat_counter),
        }

    def _cooldown_allows(self, alert: ThreatAlert) -> bool:
        signature = f"{alert.category}:{alert.title}:{alert.src_ip}:{alert.dst_ip}"
        now = alert.timestamp
        cooldown = 8 if alert.severity == "CRITICAL" else 35
        if now - self.alert_cooldowns.get(signature, 0) < cooldown:
            return False
        self.alert_cooldowns[signature] = now
        return True

    def _trim_time_deque(self, items: deque[tuple[float, int]], now: float) -> None:
        while items and now - items[0][0] > self.window_seconds:
            items.popleft()

    @staticmethod
    def _severity_for_score(score: float) -> str:
        if score >= 0.9:
            return "CRITICAL"
        if score >= 0.74:
            return "HIGH"
        if score >= 0.52:
            return "MEDIUM"
        return "LOW"

